
name: Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '배포하고자 하는 브랜치 입력'
        required: true
        default: 'develop'
      version:
        description: '배포 버전'
        required: true
        default: '9.4.15.2'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
    
    - name: Run tests
