
name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: '배포 버전'
        required: true
        default: '9.4.15.2'

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Echo variables
      run: |
        echo "version: ${{ github.event.inputs.version }}"

    - name: Do fastlane
      run: |
        cd github_actions_practice/fastlane
        BRANCH_NAME="${GITHUB_REF#refs/heads/}"  # 현재 브랜치 이름 가져오기
        fastlane setVersion newversion:${{ github.event.inputs.version }} changelog:"$BRANCH_NAME"
