
name: Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: '배포 버전'
        required: true
        default: '9.4.15.2'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Echo variables
      run: |
        echo "version: ${{ github.event.inputs.version }}"

